[theme]
primaryColor="#e694ff"
backgroundColor="#00172b"
secondaryBackgroundColor="#0083b8"
textColor="#ffffff"
[deprecation]
showPyplotGlobalUse = false

[server]
enableCORS = false
enableXsrfProtection = false
